require 'poker/card'
require 'poker/deck'
require 'poker/hole'
require 'poker/hand'
require 'poker/player'
require 'poker/table'
# all hands:
require 'poker/hand/ranked_hand'
require 'poker/hand/high_cards'
require 'poker/hand/one_pair'
require 'poker/hand/two_pair'
require 'poker/hand/three_of_a_kind'
require 'poker/hand/straight'
require 'poker/hand/flush'
require 'poker/hand/full_house'
require 'poker/hand/four_of_a_kind'
require 'poker/hand/straight_flush'
